services:
  redis:
    image: redis:7
    container_name: redis-ciu-vuelos
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

networks:
  default:
    external: true
    name: ciu-net-vuelos
